[package]
name = "yo"
version = "0.1.0"
authors = ["awave1 <artgolovin96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
